name: Build Unity Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: UNITY # Links to the UNITY environment for additional protections

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Unity Builder
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android
          unityVersion: auto

      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build/
