name: Build Unity Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: UNITY # Links to the UNITY environment for additional protections

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Unity Builder
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android
          unityVersion: auto

      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          name: Android-Build
          path: build/Android/*.apk # Adjusted to target the Android-specific folder

      - name: Commit and Push APK to GitHub
        run: |
          # Update file permissions
          sudo chmod -R 777 build/Android

          # Rename the APK file for version tracking
          mv build/Android/*.apk build/Android/MyApp-${{ github.run_number }}.apk

      - name: Deploy To HuDiNi Website
        run: |
          # BYE BYE
          curl -H "Content-Type: application/octet-stream" -H "Authorization: Bearer ${{ secrets.TOKEN_BEARER }}" -F "file=@build/Android/MyApp-${{ github.run_number }}.apk" http://content.cdirmit.co/v2/upload/misc/MyApp-${{ github.run_number }}.apk
  
  
  
