name: Build Unity Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: UNITY # Links to the UNITY environment for additional protections

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Unity Builder
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android
          unityVersion: auto

      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          name: Android-Build
          path: build/Android/*.apk # Adjusted to target the Android-specific folder

      - name: Commit and Push APK to GitHub
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

          sudo chmod -R 777 build/Android

          # Rename the APK file for version tracking
          mv build/Android/*.apk build/Android/MyApp-${{ github.run_number }}.apk

          # Commit and push the APK to the repository
          git add build/Android/MyApp-${{ github.run_number }}.apk
          git commit -m "Add new APK build (version ${{ github.run_number }})"
          git push origin main
  
  
